name: C++ CI

# Run on push and pull on cpp branch.
on:
  push:
    branches: [ cpp ]
  pull_request:
    branches: [ cpp ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglfw3-dev libglew-dev libglm-dev meson ninja-build
      - name: Generate ninja files.
        run: meson setup builddir --buildtype release
      - uses: actions/cache@v2
        with:
          path: builddir
          key: ${{ runner.os }}-meson-${{ hashFiles('meson.build') }}
          restore-keys: ${{ runner.os }}-meson-
      - name: Compile using ninja.
        run: ninja -C builddir -j `nproc`
